### ISSUE TITLE
Add pom.xml

### ISSUE THREAD

**Issue by MyBarFoo** [itsallcode/hamcrest-auto-matcher#3]
Hi there,

would it be possible to add and publish a pom.xml for hamcrest-auto-matcher? At least that is what I think I would need... I'm quite new to maven, gradle and all that....

I'm trying to build openfasttrace in offline mode to create a reproducible build and package it for NixOS. However, maven is complaining that hamcrest-auto-matcher does not provide a pom.xml. So I thought I'd ask...

Many thanks!

**Comment by kaklakariada** [comment]
Hi MyBarFoo,

If you want to build openfasttrace in offline mode you need to install hamcrest-auto-matcher into your local maven repository:

```bash
./gradlew install
```

**Comment by MyBarFoo** [comment]
Hi kaklakariada,

thank you very much for your reply and effort to help!

I hoped I could avoid managing a local repository in case _hamcrest-auto-matcher_ provided a _pom.xml_ file.

To package something for `nix` one has to convert all dependencies into a nix-specific, declarative configuration. For a maven project that can be done with: `mvn -Dmaven.repo.local=/tmp/an_empty_folder org.nixos.mvn2nix:mvn2nix-maven-plugin:mvn2nix`. As far as I understand, the mvn2nix plugin gets all its information to configure a project by recursively looking at all dependencies found in pom.xml files.

For the dependency of e.g. `openfasttrace` on `hamcrest-auto-matcher` that means the dependency is somehow skipped or ignored as hamcrest-auto-matcher doesn't provide a pom.xml file. If I want to build the auto-generated configuration of openfasttrace it fails exactly due to the missing information about hamcrest-auto-matcher:
```
...
[INFO] --------------------------------[ pom ]---------------------------------
[WARNING] The POM for com.github.kaklakariada:hamcrest-auto-matcher:jar:0.4.3 is missing, no dependency information available
...
[ERROR] Failed to execute goal on project openfasttrace-parent: Could not resolve dependencies for project org.itsallcode.openfasttrace:openfasttrace-parent:pom:3.0.2: Cannot access jcenter (https://jcenter.bintray.com/) in offline mode and the artifact com.github.kaklakariada:hamcrest-auto-matcher:jar:0.4.3 has not been downloaded from it before. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
...
```

To work around that, I would have to convert the gradle configuration of `hamcrest-auto-matcher` to a nix-configuration first and then use that generated nix-configuration to set up the local maven repository for the `mvn2nix`-conversion of `openfasttrace`.

As such an integration is hard to get right and to maintain, I'm just wondering if it would somehow be possible to _export_ the `pom.xml` file, as generated by `gradlew install`, in a way that it can be retrieved automatically by the `mvn2nix` plugin? Or is it that `hamcrest-auto-matcher` can be _either_ a gradle _or_ a maven project and so adding a `pom.xml` in the right place is therefore impossible?

Many thanks

**Comment by kaklakariada** [comment]
Hi @MyBarFoo,

I am not familiar with nix, but there is a tool called gradle2nix (https://github.com/tadfisher/gradle2nix). Maybe this is what you need?

Do you really need `hamcrest-auto-matcher` for building `openfasttrace`? It is only required for testing, so you could skip the tests with `-DskipTests`.

I could add a `pom.xml` to `hamcrest-auto-matcher` but that would be duplicate code.

**Comment by kaklakariada** [comment]
Closing after long time of inactivity
